### ISSUE TITLE
launch

### ISSUE THREAD

**Issue by hxhging** [bpingris/japscanhacker#1]
Hi,
I would like to know how this software work ?
Thanks

**Comment by bpingris** [comment]
Hey,
You might want to check for the [release page](https://github.com/BenoitPingris/japscanhacker/releases/tag/1.0.0) which contains a binary that *should* work ootb for linux.
If it does not work, you can try to pull and build yourself the project after installing the [go toolchain](https://golang.org/doc/install)

Then to launch the program (once compiled), you can do the following:
`./japscanhacker -u https://www.japscan.se/lecture-en-ligne/one-piece/1010/4.html`
And it should download the image and store it on your current pwd with a timestamped name

**Comment by hxhging** [comment]
i downloaded go but i don't know how to use it with this command '-u ' it's on go or on the terminal ?

**Comment by bpingris** [comment]
on what platform are you on?
If on linux, you might want to try to download this [binary](https://github.com/BenoitPingris/japscanhacker/releases/download/1.0.0/japscanhacker), then simply go to your `Downloads` folder, and from the terminal run the following command:
```sh
chmod +x japscanhacker
./japscanhacker -u https://www.japscan.se/lecture-en-ligne/one-piece/1010/4.html
```

If you're on windows I can compile for you a windows compatible binary, then you'll have to run this from a cmd (or powershell, it might also work):
```sh
./japscanhacker -u https://www.japscan.se/lecture-en-ligne/one-piece/1010/4.html
```

**Comment by hxhging** [comment]
thanks i am on linux but i have that " ./japscanhacker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./japscanhacker) "

**Comment by bpingris** [comment]
Ok I see what your error is, I'll try to rebuild it with a flag I forgot to use. I'll publish another binary here, thanks for giving me your error

**Comment by bpingris** [comment]
Ok could you try with this [one](https://github.com/BenoitPingris/japscanhacker/releases/download/1.0.1/japscanhacker)?

**Comment by hxhging** [comment]
thanks it works and is it possible to download the whole chapter directly ?

**Comment by bpingris** [comment]
Nice!
No, right now you can only download one page at a time, I could take a look to see how I could implement that

**Comment by hxhging** [comment]
ok thanks for your help
